// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yandex-cloud/alb-ingress/pkg/builders (interfaces: TargetGroupFinder)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	apploadbalancer "github.com/yandex-cloud/go-genproto/yandex/cloud/apploadbalancer/v1"
	reflect "reflect"
)

// MockTargetGroupFinder is a mock of TargetGroupFinder interface
type MockTargetGroupFinder struct {
	ctrl     *gomock.Controller
	recorder *MockTargetGroupFinderMockRecorder
}

// MockTargetGroupFinderMockRecorder is the mock recorder for MockTargetGroupFinder
type MockTargetGroupFinderMockRecorder struct {
	mock *MockTargetGroupFinder
}

// NewMockTargetGroupFinder creates a new mock instance
func NewMockTargetGroupFinder(ctrl *gomock.Controller) *MockTargetGroupFinder {
	mock := &MockTargetGroupFinder{ctrl: ctrl}
	mock.recorder = &MockTargetGroupFinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTargetGroupFinder) EXPECT() *MockTargetGroupFinderMockRecorder {
	return m.recorder
}

// FindTargetGroup mocks base method
func (m *MockTargetGroupFinder) FindTargetGroup(arg0 context.Context, arg1 string) (*apploadbalancer.TargetGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindTargetGroup", arg0, arg1)
	ret0, _ := ret[0].(*apploadbalancer.TargetGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindTargetGroup indicates an expected call of FindTargetGroup
func (mr *MockTargetGroupFinderMockRecorder) FindTargetGroup(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindTargetGroup", reflect.TypeOf((*MockTargetGroupFinder)(nil).FindTargetGroup), arg0, arg1)
}
