# Created manually, because kubebuilder can not generate `oneOf` validation
- op: add
  path: "/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/sessionAffinity/oneOf"
  value:
  - properties:
    required: ["connection"]
  - properties:
    required: ["cookie"]
  - properties:
    required: ["header"]

- op: add
  path: "/spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/backends/items/properties/healthChecks/items/required/-"
  value: grpc
