# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-leader-election-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ template "yc-alb-ingress-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-role
rules:
- apiGroups:
  - alb.yc.io
  resources:
  - grpcbackendgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alb.yc.io
  resources:
  - grpcbackendgroups/finalizers
  verbs:
  - update
- apiGroups:
  - alb.yc.io
  resources:
  - grpcbackendgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - alb.yc.io
  resources:
  - httpbackendgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - "*"
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - alb.yc.io
  resources:
  - httpbackendgroups/finalizers
  verbs:
  - update
- apiGroups:
  - alb.yc.io
  resources:
  - httpbackendgroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - alb.yc.io
  resources:
  - ingressgroupsettings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alb.yc.io
  resources:
  - ingressgroupstatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - patch
  - update
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "yc-alb-ingress-controller.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ template "yc-alb-ingress-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
