{{/* Be able to set secret outside if saKeySecretKey is empty */}}
{{ if .Values.saKeySecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.saKeySecretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.saKeySecretKeyFile }} : {{ .Values.saKeySecretKey | default "" | b64enc }}
{{ end }}
